<?php
header('Content-type: text/html; charset=utf-8');
session_start();
if (! $_SESSION['admin'])
    header('Location: adminavt.php');
?>
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--    <title>Страница</title>-->
<!--    <meta charset="utf-8">-->
<!--</head>-->
<!--<body>-->
<!--<form action="newart.php" method="post">-->
<!--    <p>Название статьи:</p>-->
<!--    <input name="nameart">-->
<!--    <p>Текст статьи:</p>-->
<!--    <textarea name="text1"></textarea>-->
<!--    <p>Текст ссылки в меню:</p>-->
<!--    <input name="menu">-->
<!--    <input type="submit" value="Добавить статью">-->
<!--</form>-->
<!--</body>-->
<!--</html>-->


<!DOCTYPE html>
<html>
<head>
    <title>Страница</title>
    <meta charset="utf-8">
</head>
<body>
<form action="newart.php" method="post">
    <p>Марка:</p>
    <input input type="text" name="marc">
    <p>Модель:</p>
    <input input type="text" name="model">
    <p>Тип кузова:</p>
    <input input type="text" name="class">
    <p>Сегмент:</p>
    <input input type="text" name="label">
    <p>Год:</p>
    <input input type="number" name="price">
    <p>Цвет:</p>
    <input input type="text" name="color">
    <p>Двигатель:</p>
    <input input type="text" name="engine">
    <p>Коробка передач:</p>
    <input input type="text" name="transmission">
    <input type="submit" value="Добавить статью">
</form>
</body>
</html>